name: 'Figma Cursor Theme Generator'
description: 'GitHub Action that generates a cursor theme from a Figma file, and exports additional assets.'
inputs:
  figma_access_token:
    description: 'Your personal Figma access token.'
    required: true
  figma_file_key:
    description: 'The `key` of the Figma file containing the cursor theme. Can be found in the url to of a figma file. `https://www.figma.com/file/:key/:title`'
    required: true
  sprite_component_set_id:
    description: 'Figma node ID of the sprite component set.'
    required: true
  alias_component_set_id:
    description: 'Figma node ID of the alias component set.'
    required: true
  theme_name:
    description: 'Name of the cursor theme.'
    required: true
    default: 'Generated Cursor Theme'
  theme_comment:
    description: 'Short comment or description of the cursor theme.'
    required: false
    default: 'This is a generated cursor theme.'
  output_directory:
    description: 'The directory to download assets and generate the cursor theme into.'
    required: false
    default: 'build'
outputs:
  version:
    description: 'The current version of the Figma file.'
  theme_directory:
    description: 'Directory containing the generated cursor theme and its variants.'
  export_directory:
    description: 'Directory containing exports defined in the Figma file.'
  svg_directory:
    description: 'Directory containing all sprites rendered as svg files.'

runs:
  using: 'node12'
  main: 'dist/index.js'