name: 'Figma Export Action'
description: 'GitHub Action that renders and downloads all defined exports of a Figma file that doesn't contain any conflicting exports.'
inputs:
  figma_access_token:
    description: 'Your personal figma access token.'
    required: true
  figma_file_key:
    description: 'Key of the file to render and download exports from. (https://www.figma.com/file/FIGMA_FILE_KEY/filename)'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'