name: 'Figma Export Action'
description: 'GitHub Action that renders and downloads all defined exports of a Figma file that doesn''t contain any conflicting exports.'
inputs:
  figma_access_token:
    description: 'Personal Figma access token.'
    required: true
  figma_file_key:
    description: 'Key of the file to render and download exports from. (https://www.figma.com/file/FIGMA_FILE_KEY/filename)'
    required: true
  output_directory:
    description: 'The directory to download the rendered exports to.'
    required: false
    default: 'build/export'

runs:
  using: 'node12'
  main: '../dist/figma-export/index.js'